name: tccguilherme
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_messaging: ^14.9.2
  flutter_local_notifications: ^17.1.2
  http: ^1.2.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.0
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.1
  url_launcher: ^6.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/